default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Coupon_wheel_app_development
  username: dbuser
  password: slowsnow82

test:
  <<: *default
  database: Coupon_wheel_app_test
  username: dbuser
  password: slowsnow82

production:
  <<: *default
  database: Coupon_wheel_app_production
  username: dbuser
  password: slowsnow82
