default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Coupon_wheel_app_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: Coupon_wheel_app_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: Coupon_wheel_app_production
  username: Coupon_wheel_app
  password: <%= ENV['COUPON_WHEEL_APP_DATABASE_PASSWORD'] %>
